name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Replace environment variables
      env:
        SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      run: |
        # Replace placeholders in index.html with actual environment values
        sed -i "s/{{SITE_PASSWORD}}/$SITE_PASSWORD/g" index.html
        sed -i "s/{{ADMIN_PASSWORD}}/$ADMIN_PASSWORD/g" index.html
        sed -i "s/{{FIREBASE_API_KEY}}/$FIREBASE_API_KEY/g" index.html
        sed -i "s/{{FIREBASE_AUTH_DOMAIN}}/$FIREBASE_AUTH_DOMAIN/g" index.html
        sed -i "s|{{FIREBASE_DATABASE_URL}}|$FIREBASE_DATABASE_URL|g" index.html
        sed -i "s/{{FIREBASE_PROJECT_ID}}/$FIREBASE_PROJECT_ID/g" index.html
        sed -i "s/{{FIREBASE_STORAGE_BUCKET}}/$FIREBASE_STORAGE_BUCKET/g" index.html
        sed -i "s/{{FIREBASE_MESSAGING_SENDER_ID}}/$FIREBASE_MESSAGING_SENDER_ID/g" index.html
        sed -i "s/{{FIREBASE_APP_ID}}/$FIREBASE_APP_ID/g" index.html
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main'